version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "user05-mypage"

phases:
  install:
    runtime-versions:
      java: corretto8
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $IMAGE_REPO_NAME
      - echo $AWS_ACCOUNT_ID
      - echo $AWS_DEFAULT_REGION
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo start command
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn package -Dmaven.test.skip=true
      - docker build -t 879772956301.dkr.ecr.ca-central-1.amazonaws.com/user05-mypage:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 879772956301.dkr.ecr.ca-central-1.amazonaws.com/user05-mypage:latest

cache:
  paths:
    - '/root/.m2/**/*'
